server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location = /synapse {
    return 302 /synapse/;
  }

  location /synapse/ {
    rewrite ^/synapse/?(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }
}
