ALTER TABLE memory_backfill_batches
  ADD COLUMN IF NOT EXISTS dropped_event_like INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS kept_durable INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS trusted_bypass INTEGER NOT NULL DEFAULT 0;
